--- 
- 
  hosts: localhost
  connection: local
  gather_facts: false

  tasks: 
    - 
      ec2: 
        image: ami-1c552a76
        instance_type: t2.micro
        key_name: devops3
        region: us-east-1
        wait: yes
        #state: running
        exact_count: 2
        count_tag:
          Name: M3
        instance_tags:
          Name: M3
      name: "Provision a set of instances"      
      register: ec2

    - 
      name: "Add all instance public IPs to host group"
      add_host: "hostname={{ item.public_ip }} groups=ec2hosts"
      with_items: ec2.instances

    - 
      name: Wait until SSH is available
      local_action: 
        module: wait_for 
        host: "{{ item.public_ip }}"
        port: 22 
        delay: 60 
        timeout: 320 
        state: started
      with_items: ec2.instances