--- 
- 
  name: "stopping running instances"
  hosts: security_group_*
  connection: local
  gather_facts: true
  vars:
    region: "us-east-1"
  tasks:
    - 
      name: stopping instance {{ ec2_id }}
      ec2:
        region: '{{ region }}'
        instance_tags:
          Name: M3     
        state: stopped
        wait: True
        instance_ids: '{{ ec2_id }}'

- 
  name: "starting stopped instances"
  hosts: security_group_*
  connection: local
  gather_facts: true
  vars:
    region: "us-east-1"
  tasks:
    - 
      name: starting instances {{ ec2_id }}
      ec2:
        region: '{{ region }}'
        instance_tags:
          Name: M3     
        state: running
        wait: True
        instance_ids: '{{ ec2_id }}'
        #with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id']
