--- 
- 
  hosts: localhost
  connection: local
  gather_facts: false

  tasks: 
    - 
      ec2: 
        image: ami-1c552a76
        instance_type: t2.micro
        key_name: devops3
        region: us-east-1
        wait: yes
        #state: running
        exact_count: 1
        count_tag:
          Name: M3
        instance_tags:
          Name: M3
      name: "Provision a set of instances"      
      register: ec2

    #- pause: minutes=5 
    - 
      name: "Add all instance public IPs to host group"
      add_host: "hostname={{ item.public_ip }} groups=ec2hosts"
      with_items: ec2.instances

    - 
      name: Wait until SSH is available
      local_action: 
        module: wait_for 
        host: "{{ item.public_ip }}"
        port: 22 
        delay: 60 
        timeout: 320 
        state: started
      with_items: ec2.instances

    # - 
    #   name: Register instance with ELB
    #   local_action:
    #     module: ec2_elb
    #     region: us-east-1
    #     ec2_elbs: 'DevOpsLB'
    #     instance_id: '{{ item.instace_id }}'
    #     state: present
    #   with_items: ec2.instances  
    #   sudo: false

- 
  hosts: ec2hosts
  gather_facts: false
  name: configuration play
  user: ubuntu
  tasks: 
    - 
      name: "Installs maven and jdk"
      sudo: yes
      apt: "pkg=maven state=installed update_cache=true"
      apt: "pkg=default-jdk state=installed update_cache=true"

 
